<?php
$members = array( 
		array( "id" =>  "yokoyama",
          "name" 	=>  "Kaichi Yokoyama",
		  "first"	=>	"Kaichi",
		  "last"	=>	"Yokoyama",
		  "desc"	=>	"Kaichi is the President & CEO of Moon Creative Lab. At Moon, Kaichi oversees the strategic direction of the business, manages day-to-day operations, and selects and mentors entrepreneurs-in-residence. At Mitsui & Co., he's worked on everything from building supply chains in Europe to growing healthcare businesses across Asia. He's spent one fourth of his life in Europe (Italy and Belgium), holds a PED diploma from IMD, and a BA in Economics from Keio University. In his spare time, he loves to play golf and lacrosse, explore the outdoors and go dive for nudibranchs.",
        ),
		array( "id" =>  "ph",
          "name" 	=>  "Pei-han Lim",
		  "first"	=>	"Pei-han",
		  "last"	=>	"Lim",
		  "desc"	=>	"PH is a Venture Designer at Moon Palo Alto, responsible for the Asia Pacific region where she is originally from. Her role is to create new ventures with real-world impact together with entrepreneurs-in-residence. At Mitsui & Co., she worked closely with the dynamic South East and West economies and spent some time in the Mineral and Metal Resources Division. She studied Economics in National University of Singapore. During her free time, she enjoys reading a book and hanging out with her imaginary dogs.",
        ),
		array( "id" =>  "tsuji",
          "name" 	=>  "Rieko Tsuji",
		  "first"	=>	"Rieko",
		  "last"	=>	"Tsuji",
		  "desc"	=>	"Rieko is the Digital Communication Designer of Moon Creative Lab, responsible for developing and incorporating new technology to support projects from a digital-lens. At Mitsui & Co., she worked on developing a new AI-powered service out of the New York office as a product manager and contributed as a researcher at Mitsui's in-house think tank (Mitsui Global Strategic Studies Institute) in the field of AI, wireless tech and XR. She is also a Ph.D. candidate at Tokyo Institute of Technology and a visiting scholar at New York University. She has developed a Computer Shogi (Japanese Chess) program during her university years. You may have noticed, she is a techie, you will find her on computer to try new technology whenever she has some spare time!",
        ),
		array( "id" =>  "kitashiro",
          "name" 	=>  "Natsuki Kitashiro",
		  "first"	=>	"Natsuki",
		  "last"	=>	"Kitashiro",
		  "desc"	=>	"Natsuki is a Venture Designer at Moon Tokyo. Her role is to create new ventures with real-world impact together with entrepreneurs-in-residence. At Mitsui & Co., she's worked on everything from developing condominiums in urban areas of Tokyo, managing school lunch catering service in Japan to importing/exporting food from Vietnam. She studied Architectural Structure and Design in Keio University. Outside of work, you're likely to find Natsuki on a tennis court or sipping miso soup (her favorite food!).",
        ),
		array( "id" =>  "fujii",
          "name" 	=>  "Shinsuke Fujii",
		  "first"	=>	"Shinsuke",
		  "last"	=>	"Fujii",
		  "desc"	=>	"Shinsuke Fujii is a Moon Committee member responsible for overseeing Moon's overall strategy as well as selecting future Moon entrepreneurs-in-residence. At Mitsui & Co., he is currently Representative Director and Executive Vice President of Mitsui, overseeing Corporate Planning and Strategy. <br /><br />Previously, Shinsuke has lead several departments within the Metal Sector and Non Ferrous Material Sector. He was President & CEO of Mitsui & Co. Brazil, Executive Managing Officer and General Manager of Investment Administrative Division. He holds a bachelor's degree in Law from The University of Tokyo and enjoys playing golf and spending time with his colleagues and friends.",
        ),
		array( "id" =>  "iwashita",
          "name" 	=>  "Kei Iwashita",
		  "first"	=>	"Kei",
		  "last"	=>	"Iwashita",
		  "desc"	=>	"Kei is a Business Design Lead at IDEO Tokyo, where she focuses on creating human-centered, innovative business models that unlock new ways for companies to grow. Prior to IDEO, Kei was a management consultant and joined Spotify Japan as employee #4 to launch the service in Japan. Kei sometimes moonlights as a curry chef on weekends and is a self-proclaimed foodie - go to her for the latest on restaurant recommendations! ",
        ),
		array( "id" =>  "matsui",
          "name" 	=>  "Toru Matsui",
		  "first"	=>	"Toru",
		  "last"	=>	"Matsui",
		  "desc"	=>	"Toru Matsui is a Director of Moon as well as a Moon Committee member responsible for overseeing overall Moon strategy as well as for selecting future Moon entrepreneurs-in-residence. At Mitsui & Co. he has close to 30 year experience in the Oil & Gas industry where he was Head of Exploration & Production Division before becoming General Manager of Corporate Planning and Strategy Division having worked at Mitsui & Co.'s USA, Australia and Tokyo offices. He has spent most of his childhood growing up in USA, fluent in English and Japanese and holds a LL.B from Keio University. His weekend joy is to play with his son as his best friend, a space where he reconnects with his creative energy.",
        ),
		array( "id" =>  "peng",
          "name" 	=>  "Mike Peng",
		  "first"	=>	"Mike",
		  "last"	=>	"Peng",
		  "desc"	=>	"Mike Peng is a Partner, co-managing director and co-founder of IDEO Tokyo. In his role, Mike sets the strategic direction of the business, mentors designers, and creates new offerings for Japan and throughout Asia. Mike graduated from UC Berkeley with a degree in Neuroscience and teaches regularly at Copenhagen Institute of Interaction Design (CIID). In addition to being a competitive tennis player, Mike is also an avid hip-hop dancer who finds solace in reality television.",
        ),
		array( "id" =>  "kometani",
          "name" 	=>  "Yoshio Kometani",
		  "first"	=>	"Yoshio",
		  "last"	=>	"Kometani",
		  "desc"	=>	"Yoshio Kometani is a Moon Committee member responsible for overseeing Moon's overall strategy as well as selecting future Moon entrepreneurs-in-residence. At Mitsui & Co, he is currently Executive Managing Officer responsible for Infrastructure Projects Business Unit, Mobility Business Units, and Digital Transformation.<br /><br />Yoshio has worked at Mitsui for over 30 years, previously holding the position of Chief Operating Officer of Infrastructure Projects Business Unit. He holds a bachelor's degree in Engineering from The University of Tokyo. He is passionate about ice hockey and also enjoys traveling with his family on vacation and experiencing new cultures.",
        ),
		array( "id" =>  "akiyoshi",
          "name" 	=>  "Ryosuke Akiyoshi",
		  "first"	=>	"Ryosuke",
		  "last"	=>	"Akiyoshi",
		  "desc"	=>	"Ryosuke is the Head of Tokyo of Moon Creative Lab. At Moon, his role is to manage day-to-day operations at Moon Tokyo, while collaborating with Mitsui & Co. At Mitsui & Co., he specialized in business development, primary in the chemical industry ranging from upstream commodity to specialty products where he managed various investment projects. He has gained experience outside of Mitsui in the digital art and design fields as well as at a consulting firm where worked on strategic planning and lobbying for the public sector. He holds a LL.B from Kyushu University. In his spare time, he loves to read and go sea fishing - he is a master of filleting and can make a tasty dish out of most types of fish!",
        ),
		array( "id" =>  "wada",
          "name" 	=>  "Gaku Wada",
		  "first"	=>	"Gaku",
		  "last"	=>	"Wada",
		  "desc"	=>	"Gaku is a Venture Designer at Moon Palo Alto. His role is to create new ventures with real-world impact together with entrepreneurs-in-residence. At Mitsui & Co., he has worked at both headquarters in Tokyo as well as at Mitsui Dubai. He has built his career in the Oil & Gas industry, supplying critical components from all over the world, building stable and sustainable supply chains. Gaku is London-born, but raised in New Jersey, Indiana and Tokyo. He speaks fluent English and Japanese (but flunked in Chinese) and holds a BA in political science from Keio University. He's addicted to Basketball, sneakers and 90's hip hop, and recently added Camping and DIY to the mix.",
        ),
		array( "id" =>  "liang",
          "name" 	=>  "Feng Liang",
		  "first"	=>	"Feng",
		  "last"	=>	"Liang",
		  "desc"	=>	"Feng is a Venture Designer at Moon Palo Alto, responsible for China block. His role is to create new ventures with real-world impact together with entrepreneurs-in-residence. At Mitsui & Co., he's worked in Shenzhen and Hong Kong office in chemical, machinery business, as well as business development in global steel business and supply chain in EV motor. He studied International Business in Shanghai Maritime University. Outside of work, he jogs every morning to start off his day and finds time to cook whenever he can.",
        ),
		array( "id" =>  "ishikawa",
          "name" 	=>  "Takashi Ishikawa",
		  "first"	=>	"Takashi",
		  "last"	=>	"Ishikawa",
		  "desc"	=>	"Takashi is an Operation Design Lead at Moon. His role is to manage the lab's day to day business operations and to \"keep the lights on\" at Moon. At Mitsui & Co., he has experience in M&A and PMI advisory spanning across many fields, ranging from Iron & Steel, Oil & Gas, Real Estate to Renewable Energy. He holds a LL.B from Keio University. He is a soccer fanatic and usually spends his weekends either playing soccer with his friends, or travelling throughout Japan to watch J-league games.",
        ),
        array( "id" =>  "ishiyama",
          "name" 	=>  "Tsubasa Ishiyama",
		  "first"	=>	"Tsubasa",
		  "last"	=>	"Ishiyama",
		  "desc"	=>	"Tsubasa is a Strategy Design Lead at Moon. His role at Moon is to create and implement strategy, to set-up and keep the organization running, and help entrepreneurs-in-residence to design their businesses. He has diverse working experience across various industries at Mitsui & Co., including Chemical, Renewable Energy, IP, and Consumer Services. His passion is to drive business transformation and innovation in traditional industries leading multi-disciplinary teams. He holds a MBA from IMD, and a LL.B from Sophia University. He's a huge fan of spicy food - ask him for the best mapo tofu restaurants to go to!",
        ),
		array( "id" =>  "onogawa",
          "name" 	=>  "Takashi Onogawa",
		  "first"	=>	"Takashi",
		  "last"	=>	"Onogawa",
		  "desc"	=>	"Takashi is a Director of Moon. His role is to oversee overall Moon strategy and connect Moon with Mitsui & Co, Moon's parent organization. He's worked at both Mitsui & Co.'s London and Tokyo offices, developing new services in a variety of spaces ranging from Education to Sports Facility Management. Takashi holds a Certificate of Sports Operation from New York University and a BA in Commerce from Waseda University. Outside of work, he has played guitar for many years, and dreams of playing bossa nova in Copacabana when he's 80 years old.",
        ),
		array( "id" =>  "sugimoto",
          "name" 	=>  "Ryo Sugimoto",
		  "first"	=>	"Ryo",
		  "last"	=>	"Sugimoto",
		  "desc"	=>	"Ryo is a Venture Designer at Moon Tokyo. His role is to create new ventures with real-world impact together with entrepreneurs-in-residence. At Mitsui & Co., he specialized in the machinery sector where he gained experience in everything from overseas sales and marketing, setting up new companies in Myanmar and Europe, to managing investments in global affiliate companies. He grew up in China and is a frequent business traveler, having visited 20 countries and gained work experience in Russia. He holds a B.A in Engineering from the Tokyo University of Agriculture and Technology. On weekends he loves to invite friends over to enjoy his homemade dishes. If you are lucky you may be treated to a full course lunch yourself!",
        ),
		array( "id" =>  "nonomura",
          "name" 	=>  "Ken Nonomura",
		  "first"	=>	"Ken",
		  "last"	=>	"Nonomura",
		  "desc"	=>	"Kenichi is the Director of Business Design and Development at IDEO Tokyo. His focus is to bridge creativity with business, and using the combination to generate successful change and innovation. With a passion in venture design, Kenichi is also helping create new offerings to help startups and entrepreneurs in Japan. Kenichi holds an MBA from Harvard Business School and a BA in Policy Management from Keio University. A globe trotter, Kenichi has lived in London, New York, Boston, and Singapore.",
        ),		
		array( "id" =>  "kawanishi",
          "name" 	=>  "Asami Kawanishi",
		  "first"	=>	"Asami",
		  "last"	=>	"Kawanishi",
		  "desc"	=>	"Asami Kawanishi is a marketing & communication designer at Moon Tokyo. She is responsible for external and internal communications and events to bring awareness to the Moon incubation program and support the recruitment of new creative talent. Over the course of her career, she has worked across advertising, and digital B2C marketing in the entertainment industry. She holds a bachelor's degree in Commerce from Doshisha University. Outside of work she enjoys golfing, eating, and traveling abroad.",
        ),
		array( "id" =>  "radmin",
          "name" 	=>  "Brian Radmin",
		  "first"	=>	"Brian",
		  "last"	=>	"Radmin",
		  "desc"	=>	"Brian is a Director at IDEO, where he focuses on creating new ventures. Before joining IDEO, he spent time at Bertelsmann (Europe’s largest media company) where he launched an innovation lab and did corporate venture investing. Prior to that, he spent nearly a decade as an entrepreneur – founding and launching startups. He holds an MBA from Yale School of Management and a double bachelor's degree in History and Political Science from UCLA. In his free time you can find him watching eSports and scoping out the latest raw denim to purchase.",
        ),
		array( "id" =>  "onodera",
          "name" 	=>  "Yu Onodera",
		  "first"	=>	"Yu",
		  "last"	=>	"Onodera",
		  "desc"	=>	"Yu Onodera is a Lab Experience Designer at Moon Tokyo. In her role, Yu designs effective operations and engaging experiences that will power and help Moon grow. After graduating from Waseda University, Yu joined the sales team at a cosmetic company. She then joined the Embassy and Consulate General for a Latin American country in Japan after having studied Spanish in Barcelona. Even though her stomach loves Japanese food, she finds her way of thinking to still be quite Latin!",
        ),
		array( "id" =>  "webster",
          "name" 	=>  "David Webster",
		  "first"	=>	"David",
		  "last"	=>	"Webster",
		  "desc"	=>	"David Webster is a Partner at IDEO, leading the firm's practice in humanizing technology to create new value for tech giants, global brands, and startups. David is particularly focused on exploring the new affordances of emerging technologies. He regularly speaks with clients, universities, and at conferences to encounter fresh perspectives and uncharted territory for design at the intersection of 'Human-Machine-Soul-Energy.' David holds a Master's degree in Industrial Design Engineering from the Royal College of Art and a Bachelor's in Mechanical Engineering from the University of Edinburgh.",
        ),
		array( "id" =>  "schreiber",
          "name" 	=>  "Lauren Schreiber",
		  "first"	=>	"Lauren",
		  "last"	=>	"Schreiber",
		  "desc"	=>	"Lauren Schreiber is a Design Program Lead at IDEO, crafting meaningful and powerful engagements for IDEO’s clients and design community in Palo Alto. She is passionate about designing memorable experiences and the intersection of design x culture x innovation. In her role today, Lauren guides multidisciplinary teams to create and deliver best-in-class product, service, and experience design that has global impact. When not at work, Lauren spends her free time in the ocean and climbing the peaks around the SF Bay Area.",
        ),
		array( "id" =>  "nishimori",
          "name" 	=>  "Shingo Nishimori",
		  "first"	=>	"Shingo",
		  "last"	=>	"Nishimori",
		  "desc"	=>	"Shingo is an Interaction Designer at Moon Tokyo. His role is to develop digital products that can be intuitively experienced by the user. Previous to Moon, Shingo worked in the IT industry developing Android / iOS / Web applications that allow real-time communication through audio and visuals. In his spare time, Shingo likes to go solo-camping and is particularly curious about lightweight camping.",
        ),
		array( "id" =>  "chiyun",
          "name" 	=>  "Yeh Chiyun",
		  "first"	=>	"Yeh",
		  "last"	=>	"Chiyun",
		  "desc"	=>	"Yeh (YO) is a Communication Designer at Moon Tokyo. Her role is to transform idea concepts into visual elements and use graphic design and illustration to tell better brand/user stories. Yo also has a strong passion for HCD, user experience, and user interface design for digital products. Outside of work, she enjoys hiking, playing guitar, photography, visiting museums, organizing her art shows.",
        ),
 );
 
$last = count($members) - 1;
?>